### ISSUE TITLE
QuicXplo 1.0.2: App crashes when directory level which is empty get tapped

### ISSUE THREAD

**Issue by mcyusuf** [1singhmanmeet/QuicXplo#2]
#### Expected behavior
Tapping on the directory level that contains no files or folders in it should yield no activity nor crash the app
#### Actual behavior
When in a folder or directory which has no files and folders, tapping on the directory level at the top section tab makes the app crash
#### how to reproduce
1. Open device storage
2. Open a directory or folder which has no files
3. Tap the directory level on the tab at the top section
4. App crashes

* Device: Tecno K7
* Operating system: Android Nougat 7.0
#### recording of bug
https://youtu.be/kmA2jRMlIgI

#### logcat
```
05-18 09:06:59.981 I/ActivityManager(800): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.singh.multimeet.quicxplo/.ui.browse.splash.SplashScreen (has extras)} from uid 10022 on display 0
05-18 09:07:00.012 I/libPerfService(800): [perfNotifyAppState] foreground:com.singh.multimeet.quicxplo, pid:20533
05-18 09:07:00.012 I/PPS     (800): [PPSNotifyAppState] pack:com.singh.multimeet.quicxplo, com:com.singh.multimeet.quicxplo.ui.browse.home.Home, state:1,ActiveCount = 2
05-18 09:07:00.012 I/PPS     (800): [PPSNotifyAppState] nPackNum:102, pack:com.singh.multimeet.quicxplo, com:com.singh.multimeet.quicxplo.ui.browse.home.Home, state:1, pid:20533, last_boost_tid:20533
05-18 09:07:00.376 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab432000,id:3046,api:1,p:20533,c:224) connect(P): api=1 producer=(20533:com.singh.multimeet.quicxplo) producerControlledByApp=true
05-18 09:07:00.379 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab432000,id:3046,api:1,p:20533,c:224) setMaxDequeuedBufferCount: maxDequeuedBuffers = 3
05-18 09:07:00.431 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab432000,id:3046,api:1,p:20533,c:224) new GraphicBuffer needed
05-18 09:07:00.459 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab432000,id:3046,api:1,p:20533,c:224) queueBuffer: fps=0.00 dur=219192.50 max=219192.50 min=219192.50
05-18 09:07:00.464 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab432000,id:3046,api:1,p:20533,c:224) new GraphicBuffer needed
05-18 09:07:00.543 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab432000,id:3046,api:1,p:20533,c:224) new GraphicBuffer needed
05-18 09:07:07.297 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab432000,id:3046,api:1,p:20533,c:224) new GraphicBuffer needed
05-18 09:07:07.307 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab432000,id:3046,api:1,p:20533,c:224) queueBuffer: fps=0.44 dur=6847.81 max=6713.70 min=16.25
05-18 09:07:07.319 I/ActivityManager(800): START u0 {cmp=com.singh.multimeet.quicxplo/.ui.browse.Browse (has extras)} from uid 10130 on display 0
05-18 09:07:07.343 I/PPS     (800): [PPSNotifyAppState] pack:com.singh.multimeet.quicxplo, com:com.singh.multimeet.quicxplo.ui.browse.home.Home, state:0,ActiveCount = 1
05-18 09:07:07.343 I/PPS     (800): [PPSNotifyAppState] nPackNum:102, pack:com.singh.multimeet.quicxplo, com:com.singh.multimeet.quicxplo.ui.browse.home.Home, state:0, pid:20533, last_boost_tid:20533
05-18 09:07:07.353 I/PPS     (800): [PPSNotifyAppState] pack:com.singh.multimeet.quicxplo, com:com.singh.multimeet.quicxplo.ui.browse.Browse, state:1,ActiveCount = 2
05-18 09:07:07.353 I/PPS     (800): [PPSNotifyAppState] nPackNum:102, pack:com.singh.multimeet.quicxplo, com:com.singh.multimeet.quicxplo.ui.browse.Browse, state:1, pid:20533, last_boost_tid:20533
05-18 09:07:07.360 I/BufferQueueConsumer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab456000,id:3083,api:0,p:-1,c:224) setConsumerName: com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home
05-18 09:07:07.360 I/BufferQueueConsumer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab456000,id:3083,api:0,p:-1,c:224) setDefaultBufferSize: width=720 height=1280
05-18 09:07:07.371 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab432000,id:3046,api:1,p:-1,c:224) disconnect(P): api 1
05-18 09:07:07.371 I/BufferQueueConsumer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab432000,id:3046,api:1,p:-1,c:224) getReleasedBuffers: returning mask 0xffffffffffffffff
05-18 09:07:07.379 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab456000,id:3083,api:1,p:20533,c:224) connect(P): api=1 producer=(20533:com.singh.multimeet.quicxplo) producerControlledByApp=true
05-18 09:07:07.381 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab456000,id:3083,api:1,p:20533,c:224) setMaxDequeuedBufferCount: maxDequeuedBuffers = 3
05-18 09:07:07.385 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab456000,id:3083,api:1,p:20533,c:224) new GraphicBuffer needed
05-18 09:07:07.401 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab456000,id:3083,api:1,p:20533,c:224) new GraphicBuffer needed
05-18 09:07:07.404 I/WindowManager(800): Destroying surface Surface(name=com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home) called by com.android.server.wm.WindowStateAnimator.destroyDeferredSurfaceLocked:977 com.android.server.wm.WindowStateAnimator.destroyPreservedSurfaceLocked:687 com.android.server.wm.WindowManagerService.destroyPreservedSurfaceLocked:9107 com.android.server.wm.WindowAnimator.animateLocked:810 com.android.server.wm.WindowAnimator.-wrap0:-1 com.android.server.wm.WindowAnimator$1.doFrame:147 android.view.Choreographer$CallbackRecord.run:915 android.view.Choreographer.doCallbacks:715 
05-18 09:07:07.415 I/BufferQueueConsumer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab432000,id:3046,api:1,p:-1,c:-1) disconnect(C)
05-18 09:07:07.416 I/BufferQueue(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab432000,id:3046,api:1,p:-1,c:-1) ~BufferQueueCore
05-18 09:07:07.428 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab456000,id:3083,api:1,p:20533,c:224) new GraphicBuffer needed
05-18 09:07:08.509 I/BufferQueueConsumer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:0,p:-1,c:224) setConsumerName: com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse
05-18 09:07:08.509 I/BufferQueueConsumer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:0,p:-1,c:224) setDefaultBufferSize: width=1 height=1
05-18 09:07:08.521 I/BufferQueueConsumer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:0,p:-1,c:224) setDefaultBufferSize: width=720 height=1280
05-18 09:07:08.537 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:1,p:20533,c:224) connect(P): api=1 producer=(20533:com.singh.multimeet.quicxplo) producerControlledByApp=true
05-18 09:07:08.539 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:1,p:20533,c:224) setMaxDequeuedBufferCount: maxDequeuedBuffers = 3
05-18 09:07:08.658 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab456000,id:3083,api:1,p:20533,c:224) queueBuffer: fps=26.14 dur=1262.57 max=687.03 min=6.77
05-18 09:07:08.754 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:1,p:20533,c:224) new GraphicBuffer needed
05-18 09:07:08.800 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:1,p:20533,c:224) new GraphicBuffer needed
05-18 09:07:08.805 I/ActivityManager(800): Displayed com.singh.multimeet.quicxplo/.ui.browse.Browse: +1s459ms
05-18 09:07:08.825 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:1,p:20533,c:224) new GraphicBuffer needed
05-18 09:07:08.864 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab456000,id:3083,api:1,p:-1,c:224) disconnect(P): api 1
05-18 09:07:08.864 I/BufferQueueConsumer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab456000,id:3083,api:1,p:-1,c:224) getReleasedBuffers: returning mask 0xffffffffffffffff
05-18 09:07:09.753 I/WindowManager(800): Destroying surface Surface(name=com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home) called by com.android.server.wm.WindowStateAnimator.destroySurface:2137 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:948 com.android.server.wm.WindowState.destroyOrSaveSurface:2113 com.android.server.wm.WindowManagerService.tryStartExitingAnimation:3245 com.android.server.wm.WindowManagerService.relayoutWindow:3125 com.android.server.wm.Session.relayout:227 android.view.IWindowSession$Stub.onTransact:286 com.android.server.wm.Session.onTransact:148 
05-18 09:07:09.759 I/PPS     (800): [PPSNotifyAppState] pack:com.singh.multimeet.quicxplo, com:com.singh.multimeet.quicxplo.ui.browse.home.Home, state:4,ActiveCount = 1
05-18 09:07:09.759 I/PPS     (800): [PPSNotifyAppState] nPackNum:102, pack:com.singh.multimeet.quicxplo, com:com.singh.multimeet.quicxplo.ui.browse.home.Home, state:4, pid:20533, last_boost_tid:20533
05-18 09:07:09.769 I/BufferQueueConsumer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab456000,id:3083,api:1,p:-1,c:-1) disconnect(C)
05-18 09:07:09.769 I/BufferQueue(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home](this:0xab456000,id:3083,api:1,p:-1,c:-1) ~BufferQueueCore
05-18 09:07:10.182 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:1,p:20533,c:224) queueBuffer: fps=36.96 dur=1406.96 max=453.30 min=11.32
05-18 09:07:11.258 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:1,p:20533,c:224) queueBuffer: fps=27.88 dur=1076.05 max=569.73 min=14.61
05-18 09:07:12.272 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:1,p:20533,c:224) queueBuffer: fps=18.74 dur=1013.85 max=697.39 min=14.78
05-18 09:07:13.726 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:1,p:20533,c:224) queueBuffer: fps=8.94 dur=1454.06 max=1241.45 min=16.63
05-18 09:07:13.762 E/AndroidRuntime(20533): Process: com.singh.multimeet.quicxplo, PID: 20533
05-18 09:07:13.762 E/AndroidRuntime(20533): 	at com.singh.multimeet.quicxplo.ui.browse.Browse.showOrHideEmptyMessage(Browse.java:355)
05-18 09:07:13.762 E/AndroidRuntime(20533): 	at com.singh.multimeet.quicxplo.ui.browse.Browse.onCrumbSelected(Browse.java:1127)
05-18 09:07:13.762 E/AndroidRuntime(20533): 	at com.singh.multimeet.quicxplo.adapter.BreadCrumbsAdapter.lambda$onBindViewHolder$0$BreadCrumbsAdapter(BreadCrumbsAdapter.java:75)
05-18 09:07:13.762 E/AndroidRuntime(20533): 	at com.singh.multimeet.quicxplo.adapter.BreadCrumbsAdapter$$Lambda$0.onClick(Unknown Source)
05-18 09:07:13.771 W/ActivityManager(800):   Force finishing activity com.singh.multimeet.quicxplo/.ui.browse.Browse
05-18 09:07:13.852 I/AEE_AED (21382): [preset_info] pid: 20533, tid: -1361051648, name: UNKNOWN  >>> com.singh.multimeet.quicxplo <<<
05-18 09:07:13.869 I/BufferQueueConsumer(224): [Application Error: com.singh.multimeet.quicxplo](this:0xab456000,id:3085,api:0,p:-1,c:224) setConsumerName: Application Error: com.singh.multimeet.quicxplo
05-18 09:07:13.869 I/BufferQueueConsumer(224): [Application Error: com.singh.multimeet.quicxplo](this:0xab456000,id:3085,api:0,p:-1,c:224) setDefaultBufferSize: width=129 height=129
05-18 09:07:13.880 I/BufferQueueConsumer(224): [Application Error: com.singh.multimeet.quicxplo](this:0xab456000,id:3085,api:0,p:-1,c:224) setDefaultBufferSize: width=812 height=512
05-18 09:07:13.894 I/BufferQueueProducer(224): [Application Error: com.singh.multimeet.quicxplo](this:0xab456000,id:3085,api:1,p:800,c:224) connect(P): api=1 producer=(800:system_server) producerControlledByApp=false
05-18 09:07:13.896 I/BufferQueueProducer(224): [Application Error: com.singh.multimeet.quicxplo](this:0xab456000,id:3085,api:1,p:800,c:224) setMaxDequeuedBufferCount: maxDequeuedBuffers = 3
05-18 09:07:13.906 I/BufferQueueProducer(224): [Application Error: com.singh.multimeet.quicxplo](this:0xab456000,id:3085,api:1,p:800,c:224) new GraphicBuffer needed
05-18 09:07:13.921 I/BufferQueueProducer(224): [Application Error: com.singh.multimeet.quicxplo](this:0xab456000,id:3085,api:1,p:800,c:224) new GraphicBuffer needed
05-18 09:07:13.927 I/WindowManager(800): Losing delayed focus: Window{cb282e2 u0 com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse}
05-18 09:07:14.280 W/ActivityManager(800): Activity pause timeout for ActivityRecord{c78b7df u0 com.singh.multimeet.quicxplo/.ui.browse.Browse t2592 f}
05-18 09:07:14.280 I/PPS     (800): [PPSNotifyAppState] pack:com.singh.multimeet.quicxplo, com:com.singh.multimeet.quicxplo.ui.browse.Browse, state:0,ActiveCount = 0
05-18 09:07:14.280 I/PPS     (800): [PPSNotifyAppState] nPackNum:102, pack:com.singh.multimeet.quicxplo, com:com.singh.multimeet.quicxplo.ui.browse.Browse, state:0, pid:20533, last_boost_tid:20533
05-18 09:07:14.282 I/PPS     (800): [PPSNotifyAppState] pack:com.singh.multimeet.quicxplo, com:com.singh.multimeet.quicxplo.ui.browse.home.Home, state:1,ActiveCount = 1
05-18 09:07:14.282 I/PPS     (800): [PPSNotifyAppState] nPackNum:102, pack:com.singh.multimeet.quicxplo, com:com.singh.multimeet.quicxplo.ui.browse.home.Home, state:1, pid:20533, last_boost_tid:20533
05-18 09:07:17.120 W/ActivityManager(800):   Force finishing activity com.singh.multimeet.quicxplo/.ui.browse.Browse
05-18 09:07:17.128 I/BufferQueueProducer(224): [Application Error: com.singh.multimeet.quicxplo](this:0xab456000,id:3085,api:1,p:-1,c:224) disconnect(P): api 1
05-18 09:07:17.128 I/BufferQueueConsumer(224): [Application Error: com.singh.multimeet.quicxplo](this:0xab456000,id:3085,api:1,p:-1,c:224) getReleasedBuffers: returning mask 0xffffffffffffffff
05-18 09:07:17.134 W/ActivityManager(800):   Force finishing activity com.singh.multimeet.quicxplo/.ui.browse.home.Home
05-18 09:07:17.210 E/ActivityManager(800): Found activity ActivityRecord{f7d78ef u0 com.singh.multimeet.quicxplo/.ui.browse.home.Home t2592 f} in proc activity list using null instead of expected ProcessRecord{9367a23 20533:com.singh.multimeet.quicxplo/u0a130}
05-18 09:07:17.221 I/ActivityManager(800): Killing 20533:com.singh.multimeet.quicxplo/u0a130 (adj 199): crash
05-18 09:07:17.226 W/ViewRootImpl[quicxplo](800): Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=445.35645, y[0]=574.1826, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=2, eventTime=116236412, downTime=116236384, deviceId=2, source=0x1002 }
05-18 09:07:17.247 I/WindowManager(800): Destroying surface Surface(name=Application Error: com.singh.multimeet.quicxplo) called by com.android.server.wm.WindowStateAnimator.destroySurface:2137 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:948 com.android.server.wm.WindowState.destroyOrSaveSurface:2113 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:434 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:235 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:183 com.android.server.wm.WindowManagerService$H.handleMessage:8464 android.os.Handler.dispatchMessage:110 
05-18 09:07:17.253 I/BufferQueueConsumer(224): [Application Error: com.singh.multimeet.quicxplo](this:0xab456000,id:3085,api:1,p:-1,c:-1) disconnect(C)
05-18 09:07:17.254 I/BufferQueue(224): [Application Error: com.singh.multimeet.quicxplo](this:0xab456000,id:3085,api:1,p:-1,c:-1) ~BufferQueueCore
05-18 09:07:17.366 I/BufferQueueProducer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:1,p:-1,c:224) disconnect(P): api 1
05-18 09:07:17.366 I/BufferQueueConsumer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:1,p:-1,c:224) getReleasedBuffers: returning mask 0xffffffffffffffff
05-18 09:07:17.370 W/InputDispatcher(800): channel 'c8f9ab2 com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
05-18 09:07:17.371 E/InputDispatcher(800): channel 'c8f9ab2 com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home (server)' ~ Channel is unrecoverably broken and will be disposed!
05-18 09:07:17.373 W/InputDispatcher(800): channel 'cb282e2 com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
05-18 09:07:17.373 E/InputDispatcher(800): channel 'cb282e2 com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse (server)' ~ Channel is unrecoverably broken and will be disposed!
05-18 09:07:17.373 I/WindowManager(800): WIN DEATH: Window{cb282e2 u0 com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse}
05-18 09:07:17.374 W/InputDispatcher(800): Attempted to unregister already unregistered input channel 'cb282e2 com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse (server)'
05-18 09:07:17.374 I/WindowManager(800): Destroying surface Surface(name=com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse) called by com.android.server.wm.WindowStateAnimator.destroySurface:2137 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:948 com.android.server.wm.WindowState.removeLocked:1469 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2678 com.android.server.wm.WindowManagerService.removeWindowLocked:2626 com.android.server.wm.WindowState$DeathRecipient.binderDied:1800 android.os.BinderProxy.sendDeathNotice:695 <bottom of call stack> 
05-18 09:07:17.376 I/BufferQueueConsumer(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:1,p:-1,c:-1) disconnect(C)
05-18 09:07:17.382 I/BufferQueue(224): [com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.Browse](this:0xab432000,id:3084,api:1,p:-1,c:-1) ~BufferQueueCore
05-18 09:07:17.385 I/WindowManager(800): WIN DEATH: Window{c8f9ab2 u0 com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home}
05-18 09:07:17.386 W/InputDispatcher(800): Attempted to unregister already unregistered input channel 'c8f9ab2 com.singh.multimeet.quicxplo/com.singh.multimeet.quicxplo.ui.browse.home.Home (server)'

```

**Comment by 1singhmanmeet** [comment]
I just checked it will be fixed soon.
Thanks
